version: '3.9'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:15
    environment:
      POSTGRES_DB: app
      # You should definitely change the password in production
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: app
      #POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
